In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
sent = ['the glass of water', 
        'the glass of milk',
        'the cup of tea',
        'I am a good boy',
        'I am a good developer',
        'understanding the words and their meaning is important for NLP',
        'your videosare good']

In [3]:
sent

['the glass of water',
 'the glass of milk',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understanding the words and their meaning is important for NLP',
 'your videosare good']

In [4]:
## Define the vocabulary size
voc_size = 10000

In [5]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[805, 2572, 6704, 3461],
 [805, 2572, 6704, 4098],
 [805, 6703, 6704, 9296],
 [9016, 4613, 4629, 4554, 5530],
 [9016, 4613, 4629, 4554, 3961],
 [1897, 805, 7174, 7587, 6674, 742, 5932, 7499, 8454, 3761],
 [8269, 7126, 4554]]

In [7]:
## word  Embedding Representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [8]:
sent_length = 8
embedded_docs =pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0  805 2572 6704 3461]
 [   0    0    0    0  805 2572 6704 4098]
 [   0    0    0    0  805 6703 6704 9296]
 [   0    0    0 9016 4613 4629 4554 5530]
 [   0    0    0 9016 4613 4629 4554 3961]
 [7174 7587 6674  742 5932 7499 8454 3761]
 [   0    0    0    0    0 8269 7126 4554]]


In [9]:
## feature representaion
dim=10


In [12]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

c:\Users\win10\miniconda3\envs\myenv\Lib\site-packages\keras\src\layers\core\embedding.py:123: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [11]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [13]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 365ms/step


array([[[-0.04409429,  0.01991973,  0.03470636, -0.00184022,
         -0.03364359,  0.0492242 ,  0.04586879,  0.02906776,
         -0.04731956, -0.04678394],
        [-0.04409429,  0.01991973,  0.03470636, -0.00184022,
         -0.03364359,  0.0492242 ,  0.04586879,  0.02906776,
         -0.04731956, -0.04678394],
        [-0.04409429,  0.01991973,  0.03470636, -0.00184022,
         -0.03364359,  0.0492242 ,  0.04586879,  0.02906776,
         -0.04731956, -0.04678394],
        [-0.04409429,  0.01991973,  0.03470636, -0.00184022,
         -0.03364359,  0.0492242 ,  0.04586879,  0.02906776,
         -0.04731956, -0.04678394],
        [-0.0380568 , -0.04230745,  0.01885972, -0.01912308,
         -0.02191797,  0.03365448, -0.02399094,  0.01200525,
         -0.04416453,  0.03102395],
        [ 0.04840431,  0.03578096,  0.0014862 , -0.04413679,
         -0.01612068,  0.02004871,  0.0490648 ,  0.03709903,
          0.04258049, -0.03390344],
        [-0.04957452,  0.02954808, -0.02253575,  0.0

In [14]:
embedded_docs[0]


array([   0,    0,    0,    0,  805, 2572, 6704, 3461], dtype=int32)

In [16]:
model.predict(embedded_docs[:1])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step


array([[[-0.04409429,  0.01991973,  0.03470636, -0.00184022,
         -0.03364359,  0.0492242 ,  0.04586879,  0.02906776,
         -0.04731956, -0.04678394],
        [-0.04409429,  0.01991973,  0.03470636, -0.00184022,
         -0.03364359,  0.0492242 ,  0.04586879,  0.02906776,
         -0.04731956, -0.04678394],
        [-0.04409429,  0.01991973,  0.03470636, -0.00184022,
         -0.03364359,  0.0492242 ,  0.04586879,  0.02906776,
         -0.04731956, -0.04678394],
        [-0.04409429,  0.01991973,  0.03470636, -0.00184022,
         -0.03364359,  0.0492242 ,  0.04586879,  0.02906776,
         -0.04731956, -0.04678394],
        [-0.0380568 , -0.04230745,  0.01885972, -0.01912308,
         -0.02191797,  0.03365448, -0.02399094,  0.01200525,
         -0.04416453,  0.03102395],
        [ 0.04840431,  0.03578096,  0.0014862 , -0.04413679,
         -0.01612068,  0.02004871,  0.0490648 ,  0.03709903,
          0.04258049, -0.03390344],
        [-0.04957452,  0.02954808, -0.02253575,  0.0